const seedrecipes = [
    {
        title: 'Pancakes - seed',
        description: 'A delicious breakfast treat that is quick and easy to make. Perfect for a lazy Sunday morning or a special brunch.',
        ingredients: '1 cup flour, 1 cup milk, 1 egg, 2 tbsp sugar, 1 tsp baking powder, 1/2 tsp salt, 2 tbsp melted butter',
        instructions: '1. In a large bowl, whisk together the flour, sugar, baking powder, and salt. 2. In another bowl, beat the egg and then whisk in the milk and melted butter. 3. Pour the wet ingredients into the dry ingredients and stir until just combined. 4. Heat a griddle or non-stick pan over medium heat and lightly grease it. 5. Pour 1/4 cup of batter onto the griddle for each pancake. 6. Cook until bubbles form on the surface, then flip and cook until golden brown on the other side. 7. Serve warm with your favorite toppings.',
        preptime: 10,
        servings: 4,
        image: 'https://picsum.photos/seed/pancakes/1600/900',
        creator: '67a4eda0d77031cbaa4c867d',
    },
    {
        title: 'Spaghetti Bolognese - seed',
        description: 'A classic Italian pasta dish with a rich and savory meat sauce. Perfect for a hearty dinner.',
        ingredients: '200g spaghetti, 100g minced beef, 1 onion, 2 cloves garlic, 400g canned tomatoes, 2 tbsp tomato paste, 1 tsp dried oregano, 1 tsp dried basil, salt, pepper, olive oil, grated Parmesan cheese',
        instructions: '1. Cook the spaghetti according to the package instructions. 2. In a large pan, heat the olive oil over medium heat. 3. Add the chopped onion and garlic and sauté until softened. 4. Add the minced beef and cook until browned. 5. Stir in the canned tomatoes, tomato paste, oregano, basil, salt, and pepper. 6. Simmer the sauce for 20-30 minutes, stirring occasionally. 7. Drain the spaghetti and toss with the sauce. 8. Serve with grated Parmesan cheese on top.',
        preptime: 30,
        servings: 2,
        image: 'https://picsum.photos/seed/spaghetti/1600/900',
        creator: '67a4eda0d77031cbaa4c867d',
    },
    {
        title: 'Chicken Curry - seed',
        description: 'A spicy and flavorful chicken curry that is sure to warm you up. Serve with rice or naan for a complete meal.',
        ingredients: '500g chicken, 2 tbsp curry powder, 1 onion, 2 cloves garlic, 1 tbsp ginger, 400ml coconut milk, 1 tsp turmeric, 1 tsp cumin, 1 tsp coriander, salt, pepper, olive oil, fresh cilantro',
        instructions: '1. Cut the chicken into bite-sized pieces and season with salt and pepper. 2. In a large pot, heat the olive oil over medium heat. 3. Add the chopped onion, garlic, and ginger and sauté until softened. 4. Add the curry powder, turmeric, cumin, and coriander and cook for 1-2 minutes. 5. Add the chicken and cook until browned on all sides. 6. Pour in the coconut milk and bring to a simmer. 7. Cook for 20-25 minutes, until the chicken is cooked through and the sauce has thickened. 8. Garnish with fresh cilantro and serve with rice or naan.',
        preptime: 40,
        servings: 4,
        image: 'https://picsum.photos/seed/chicken-curry/1600/900',
        creator: '67a4eda0d77031cbaa4c867d',
    },
    {
        title: 'Caesar Salad - seed',
        description: 'A fresh and healthy salad with crisp lettuce, crunchy croutons, and a creamy Caesar dressing. Perfect as a side dish or a light meal.',
        ingredients: '1 head romaine lettuce, 1 cup croutons, 1/4 cup grated Parmesan cheese, 1/2 cup Caesar dressing, 1 lemon, salt, pepper',
        instructions: '1. Wash and chop the romaine lettuce. 2. In a large bowl, toss the lettuce with the croutons and grated Parmesan cheese. 3. Drizzle with Caesar dressing and toss to coat. 4. Squeeze the lemon juice over the salad and season with salt and pepper. 5. Serve immediately.',
        preptime: 15,
        servings: 2,
        image: 'https://picsum.photos/seed/caesar-salad/1600/900',
        creator: '67a4eda0d77031cbaa4c867d',
    },
    {
        title: 'Beef Tacos - seed',
        description: 'Mexican style beef tacos with seasoned minced beef, fresh lettuce, cheese, and salsa. Perfect for a quick and tasty meal.',
        ingredients: 'Taco shells, 200g minced beef, 1 onion, 2 cloves garlic, 1 tsp chili powder, 1 tsp cumin, salt, pepper, lettuce, shredded cheese, salsa, sour cream',
        instructions: '1. In a large pan, heat the olive oil over medium heat. 2. Add the chopped onion and garlic and sauté until softened. 3. Add the minced beef and cook until browned. 4. Stir in the chili powder, cumin, salt, and pepper. 5. Cook for another 5 minutes, until the beef is fully cooked and the spices are well combined. 6. Warm the taco shells according to the package instructions. 7. Fill each taco shell with the beef mixture and top with lettuce, cheese, salsa, and sour cream. 8. Serve immediately.',
        preptime: 20,
        servings: 3,
        image: 'https://picsum.photos/seed/beef-tacos/1600/900',
        creator: '67a4eda0d77031cbaa4c867d',
    },
    {
        title: 'Vegetable Stir Fry - seed',
        description: 'A quick and easy vegetable stir fry with a savory soy sauce and garlic flavor. Perfect for a healthy and delicious meal.',
        ingredients: 'Mixed vegetables (broccoli, bell peppers, carrots, snap peas), 2 cloves garlic, 1 tbsp ginger, 2 tbsp soy sauce, 1 tbsp oyster sauce, 1 tsp sesame oil, salt, pepper, olive oil, cooked rice',
        instructions: '1. Wash and chop the vegetables into bite-sized pieces. 2. In a large pan or wok, heat the olive oil over medium-high heat. 3. Add the chopped garlic and ginger and sauté for 1-2 minutes. 4. Add the vegetables and stir fry for 5-7 minutes, until they are tender but still crisp. 5. Stir in the soy sauce, oyster sauce, sesame oil, salt, and pepper. 6. Cook for another 2-3 minutes, until the vegetables are well coated with the sauce. 7. Serve over cooked rice.',
        preptime: 15,
        servings: 2,
        image: 'https://picsum.photos/seed/vegetable-stir-fry/1600/900',
        creator: '67a4eda0d77031cbaa4c867d',
    },
    {
        title: 'Chocolate Cake - seed',
        description: 'A rich and moist chocolate cake that is perfect for any occasion. Serve with a scoop of ice cream or a dollop of whipped cream.',
        ingredients: '1 1/2 cups flour, 1 cup sugar, 1/2 cup cocoa powder, 1 tsp baking powder, 1/2 tsp baking soda, 1/2 tsp salt, 1 cup milk, 1/2 cup vegetable oil, 2 eggs, 1 tsp vanilla extract, 1 cup boiling water',
        instructions: '1. Preheat the oven to 350°F (175°C). 2. Grease and flour a 9-inch round cake pan. 3. In a large bowl, whisk together the flour, sugar, cocoa powder, baking powder, baking soda, and salt. 4. Add the milk, vegetable oil, eggs, and vanilla extract and beat until smooth. 5. Gradually add the boiling water and mix until well combined. 6. Pour the batter into the prepared pan. 7. Bake for 30-35 minutes, or until a toothpick inserted into the center comes out clean. 8. Allow the cake to cool in the pan for 10 minutes, then remove from the pan and cool completely on a wire rack. 9. Frost with your favorite chocolate frosting and serve.',
        preptime: 60,
        servings: 8,
        image: 'https://picsum.photos/seed/chocolate-cake/1600/900',
        creator: '67a4eda0d77031cbaa4c867d',
    },
    {
        title: 'Grilled Cheese Sandwich - seed',
        description: 'A classic grilled cheese sandwich with gooey melted cheese and crispy golden bread. Perfect for a quick and comforting meal.',
        ingredients: '2 slices of bread, 2 slices of cheese, 1 tbsp butter',
        instructions: '1. Heat a skillet over medium heat. 2. Butter one side of each slice of bread. 3. Place one slice of bread, buttered side down, in the skillet. 4. Top with the cheese slices and the other slice of bread, buttered side up. 5. Cook until the bread is golden brown and the cheese is melted, about 2-3 minutes per side. 6. Serve immediately.',
        preptime: 10,
        servings: 1,
        image: 'https://picsum.photos/seed/grilled-cheese/1600/900',
        creator: '67a4eda0d77031cbaa4c867d',
    },
    {
        title: 'Tomato Soup - seed',
        description: 'A warm and comforting tomato soup that is perfect for a chilly day. Serve with a grilled cheese sandwich for a classic combination.',
        ingredients: '2 tbsp olive oil, 1 onion, 2 cloves garlic, 1 carrot, 2 cans (28 oz) crushed tomatoes, 2 cups vegetable broth, 1 tsp sugar, 1 tsp dried basil, salt, pepper, fresh basil for garnish',
        instructions: '1. In a large pot, heat the olive oil over medium heat. 2. Add the chopped onion, garlic, and carrot and sauté until softened. 3. Stir in the crushed tomatoes, vegetable broth, sugar, dried basil, salt, and pepper. 4. Bring to a boil, then reduce the heat and simmer for 20-25 minutes. 5. Use an immersion blender to blend the soup until smooth. 6. Serve hot, garnished with fresh basil.',
        preptime: 30,
        servings: 4,
        image: 'https://picsum.photos/seed/tomato-soup/1600/900',
        creator: '67a4eda0d77031cbaa4c867d',
    },
    {
        title: 'Omelette - seed',
        description: 'A fluffy and delicious omelette filled with your favorite ingredients. Perfect for a quick and satisfying breakfast or brunch.',
        ingredients: '3 eggs, 1/4 cup milk, salt, pepper, 1/4 cup shredded cheese, 1/4 cup diced ham, 1/4 cup chopped vegetables (bell peppers, onions, mushrooms), 1 tbsp butter',
        instructions: '1. In a bowl, whisk together the eggs, milk, salt, and pepper. 2. Heat the butter in a non-stick skillet over medium heat. 3. Pour the egg mixture into the skillet and cook until the edges start to set. 4. Sprinkle the cheese, ham, and vegetables over one half of the omelette. 5. Fold the other half of the omelette over the filling. 6. Cook for another 1-2 minutes, until the cheese is melted and the eggs are fully cooked. 7. Slide the omelette onto a plate and serve immediately.',
        preptime: 10,
        servings: 1,
        image: 'https://picsum.photos/seed/omelette/1600/900',
        creator: '67a4eda0d77031cbaa4c867d',
    },
    {
        title: 'BBQ Ribs - seed',
        description: 'Tender and flavorful BBQ ribs that are perfect for a summer cookout. Serve with your favorite sides for a complete meal.',
        ingredients: '2 racks of pork ribs, 1 cup BBQ sauce, 1/4 cup brown sugar, 1 tbsp paprika, 1 tbsp garlic powder, 1 tbsp onion powder, 1 tsp salt, 1 tsp pepper',
        instructions: '1. Preheat the oven to 300°F (150°C). 2. In a small bowl, mix together the brown sugar, paprika, garlic powder, onion powder, salt, and pepper. 3. Rub the spice mixture all over the ribs. 4. Place the ribs on a baking sheet and cover with foil. 5. Bake for 2 1/2 to 3 hours, until the ribs are tender. 6. Remove the foil and brush the ribs with BBQ sauce. 7. Increase the oven temperature to 400°F (200°C) and bake for another 15-20 minutes, until the sauce is caramelized. 8. Serve hot with additional BBQ sauce on the side.',
        preptime: 120,
        servings: 4,
        image: 'https://picsum.photos/seed/bbq-ribs/1600/900',
        creator: '67a4eda0d77031cbaa4c867d',
    },
    {
        title: 'Margarita Pizza - seed',
        description: 'A classic Italian pizza with a simple and delicious combination of tomato sauce, mozzarella cheese, and fresh basil.',
        ingredients: 'Pizza dough, 1/2 cup tomato sauce, 1 cup shredded mozzarella cheese, fresh basil leaves, olive oil, salt, pepper',
        instructions: '1. Preheat the oven to 475°F (245°C). 2. Roll out the pizza dough on a floured surface. 3. Transfer the dough to a pizza stone or baking sheet. 4. Spread the tomato sauce evenly over the dough. 5. Sprinkle the mozzarella cheese on top. 6. Bake for 10-12 minutes, until the crust is golden brown and the cheese is melted and bubbly. 7. Remove from the oven and top with fresh basil leaves. 8. Drizzle with olive oil and season with salt and pepper. 9. Slice and serve hot.',
        preptime: 20,
        servings: 2,
        image: 'https://picsum.photos/seed/margarita-pizza/1600/900',
        creator: '67a4eda0d77031cbaa4c867d',
    },
    {
        title: 'Fish Tacos - seed',
        description: 'Fresh and tasty fish tacos with a zesty lime and cilantro slaw. Perfect for a light and flavorful meal.',
        ingredients: 'Taco shells, 400g fish fillets (such as cod or tilapia), 1/2 cup flour, 1 tsp chili powder, 1 tsp cumin, salt, pepper, 1/4 cup mayonnaise, 1/4 cup sour cream, 1 lime, 1/4 cup chopped cilantro, 2 cups shredded cabbage, olive oil',
        instructions: '1. In a shallow dish, mix together the flour, chili powder, cumin, salt, and pepper. 2. Dredge the fish fillets in the flour mixture, shaking off any excess. 3. Heat the olive oil in a large pan over medium-high heat. 4. Cook the fish fillets for 3-4 minutes per side, until golden brown and cooked through. 5. In a small bowl, mix together the mayonnaise, sour cream, lime juice, and chopped cilantro. 6. In a large bowl, toss the shredded cabbage with the dressing. 7. Warm the taco shells according to the package instructions. 8. Fill each taco shell with a piece of fish and top with the slaw. 9. Serve immediately.',
        preptime: 20,
        servings: 3,
        image: 'https://picsum.photos/seed/fish-tacos/1600/900',
        creator: '67a4eda0d77031cbaa4c867d',
    },
    {
        title: 'Lemonade - seed',
        description: 'Refreshing homemade lemonade that is perfect for a hot summer day. Sweet, tangy, and incredibly easy to make.',
        ingredients: '6 lemons, 1 cup sugar, 6 cups water, ice, lemon slices for garnish',
        instructions: '1. Juice the lemons to make about 1 cup of lemon juice. 2. In a small saucepan, combine the sugar and 1 cup of water. 3. Heat over medium heat, stirring until the sugar is dissolved, to make a simple syrup. 4. In a large pitcher, combine the lemon juice, simple syrup, and the remaining 5 cups of water. 5. Stir well and refrigerate until chilled. 6. Serve over ice, garnished with lemon slices.',
        preptime: 10,
        servings: 4,
        image: 'https://picsum.photos/seed/lemonade/1600/900',
        creator: '67a4eda0d77031cbaa4c867d',
    },
    {
        title: 'Apple Pie - seed',
        description: 'Classic apple pie with a flaky crust and a sweet, spiced apple filling. Perfect for dessert or a special occasion.',
        ingredients: '6 cups sliced apples, 1 cup sugar, 2 tbsp flour, 1 tsp cinnamon, 1/4 tsp nutmeg, 1/4 tsp salt, 1 tbsp lemon juice, 2 pie crusts, 2 tbsp butter, 1 egg, 1 tbsp milk',
        instructions: '1. Preheat the oven to 425°F (220°C). 2. In a large bowl, toss the sliced apples with the sugar, flour, cinnamon, nutmeg, salt, and lemon juice. 3. Roll out one pie crust and fit it into a 9-inch pie plate. 4. Fill the crust with the apple mixture and dot with butter. 5. Roll out the second pie crust and place it over the filling. 6. Trim and crimp the edges to seal. 7. Cut a few slits in the top crust to allow steam to escape. 8. In a small bowl, beat the egg with the milk and brush it over the top crust. 9. Bake for 45-50 minutes, until the crust is golden brown and the filling is bubbly. 10. Allow the pie to cool before serving.',
        preptime: 90,
        servings: 8,
        image: 'https://picsum.photos/seed/apple-pie/1600/900',
        creator: '67a4eda0d77031cbaa4c867d',
    },
    {
        title: 'Pancakes - seed',
        description: 'A delicious breakfast treat that is quick and easy to make. Perfect for a lazy Sunday morning or a special brunch.',
        ingredients: '1 cup flour, 1 cup milk, 1 egg, 2 tbsp sugar, 1 tsp baking powder, 1/2 tsp salt, 2 tbsp melted butter',
        instructions: '1. In a large bowl, whisk together the flour, sugar, baking powder, and salt. 2. In another bowl, beat the egg and then whisk in the milk and melted butter. 3. Pour the wet ingredients into the dry ingredients and stir until just combined. 4. Heat a griddle or non-stick pan over medium heat and lightly grease it. 5. Pour 1/4 cup of batter onto the griddle for each pancake. 6. Cook until bubbles form on the surface, then flip and cook until golden brown on the other side. 7. Serve warm with your favorite toppings.',
        preptime: 10,
        servings: 4,
        image: 'https://picsum.photos/seed/pancakes/1600/900',
        creator: '67a4eda0d77031cbaa4c867d',
    },
    {
        title: 'Spaghetti Bolognese - seed',
        description: 'A classic Italian pasta dish with a rich and savory meat sauce. Perfect for a hearty dinner.',
        ingredients: '200g spaghetti, 100g minced beef, 1 onion, 2 cloves garlic, 400g canned tomatoes, 2 tbsp tomato paste, 1 tsp dried oregano, 1 tsp dried basil, salt, pepper, olive oil, grated Parmesan cheese',
        instructions: '1. Cook the spaghetti according to the package instructions. 2. In a large pan, heat the olive oil over medium heat. 3. Add the chopped onion and garlic and sauté until softened. 4. Add the minced beef and cook until browned. 5. Stir in the canned tomatoes, tomato paste, oregano, basil, salt, and pepper. 6. Simmer the sauce for 20-30 minutes, stirring occasionally. 7. Drain the spaghetti and toss with the sauce. 8. Serve with grated Parmesan cheese on top.',
        preptime: 30,
        servings: 2,
        image: 'https://picsum.photos/seed/spaghetti/1600/900',
        creator: '67a4eda0d77031cbaa4c867d',
    },
    {
        title: 'Chicken Curry - seed',
        description: 'A spicy and flavorful chicken curry that is sure to warm you up. Serve with rice or naan for a complete meal.',
        ingredients: '500g chicken, 2 tbsp curry powder, 1 onion, 2 cloves garlic, 1 tbsp ginger, 400ml coconut milk, 1 tsp turmeric, 1 tsp cumin, 1 tsp coriander, salt, pepper, olive oil, fresh cilantro',
        instructions: '1. Cut the chicken into bite-sized pieces and season with salt and pepper. 2. In a large pot, heat the olive oil over medium heat. 3. Add the chopped onion, garlic, and ginger and sauté until softened. 4. Add the curry powder, turmeric, cumin, and coriander and cook for 1-2 minutes. 5. Add the chicken and cook until browned on all sides. 6. Pour in the coconut milk and bring to a simmer. 7. Cook for 20-25 minutes, until the chicken is cooked through and the sauce has thickened. 8. Garnish with fresh cilantro and serve with rice or naan.',
        preptime: 40,
        servings: 4,
        image: 'https://picsum.photos/seed/chicken-curry/1600/900',
        creator: '67a4eda0d77031cbaa4c867d',
    },
    {
        title: 'Caesar Salad - seed',
        description: 'A fresh and healthy salad with crisp lettuce, crunchy croutons, and a creamy Caesar dressing. Perfect as a side dish or a light meal.',
        ingredients: '1 head romaine lettuce, 1 cup croutons, 1/4 cup grated Parmesan cheese, 1/2 cup Caesar dressing, 1 lemon, salt, pepper',
        instructions: '1. Wash and chop the romaine lettuce. 2. In a large bowl, toss the lettuce with the croutons and grated Parmesan cheese. 3. Drizzle with Caesar dressing and toss to coat. 4. Squeeze the lemon juice over the salad and season with salt and pepper. 5. Serve immediately.',
        preptime: 15,
        servings: 2,
        image: 'https://picsum.photos/seed/caesar-salad/1600/900',
        creator: '67a4eda0d77031cbaa4c867d',
    },
    {
        title: 'Beef Tacos - seed',
        description: 'Mexican style beef tacos with seasoned minced beef, fresh lettuce, cheese, and salsa. Perfect for a quick and tasty meal.',
        ingredients: 'Taco shells, 200g minced beef, 1 onion, 2 cloves garlic, 1 tsp chili powder, 1 tsp cumin, salt, pepper, lettuce, shredded cheese, salsa, sour cream',
        instructions: '1. In a large pan, heat the olive oil over medium heat. 2. Add the chopped onion and garlic and sauté until softened. 3. Add the minced beef and cook until browned. 4. Stir in the chili powder, cumin, salt, and pepper. 5. Cook for another 5 minutes, until the beef is fully cooked and the spices are well combined. 6. Warm the taco shells according to the package instructions. 7. Fill each taco shell with the beef mixture and top with lettuce, cheese, salsa, and sour cream. 8. Serve immediately.',
        preptime: 20,
        servings: 3,
        image: 'https://picsum.photos/seed/beef-tacos/1600/900',
        creator: '67a4eda0d77031cbaa4c867d',
    },
    {
        title: 'Vegetable Stir Fry - seed',
        description: 'A quick and easy vegetable stir fry with a savory soy sauce and garlic flavor. Perfect for a healthy and delicious meal.',
        ingredients: 'Mixed vegetables (broccoli, bell peppers, carrots, snap peas), 2 cloves garlic, 1 tbsp ginger, 2 tbsp soy sauce, 1 tbsp oyster sauce, 1 tsp sesame oil, salt, pepper, olive oil, cooked rice',
        instructions: '1. Wash and chop the vegetables into bite-sized pieces. 2. In a large pan or wok, heat the olive oil over medium-high heat. 3. Add the chopped garlic and ginger and sauté for 1-2 minutes. 4. Add the vegetables and stir fry for 5-7 minutes, until they are tender but still crisp. 5. Stir in the soy sauce, oyster sauce, sesame oil, salt, and pepper. 6. Cook for another 2-3 minutes, until the vegetables are well coated with the sauce. 7. Serve over cooked rice.',
        preptime: 15,
        servings: 2,
        image: 'https://picsum.photos/seed/vegetable-stir-fry/1600/900',
        creator: '67a4eda0d77031cbaa4c867d',
    },
    {
        title: 'Chocolate Cake - seed',
        description: 'A rich and moist chocolate cake that is perfect for any occasion. Serve with a scoop of ice cream or a dollop of whipped cream.',
        ingredients: '1 1/2 cups flour, 1 cup sugar, 1/2 cup cocoa powder, 1 tsp baking powder, 1/2 tsp baking soda, 1/2 tsp salt, 1 cup milk, 1/2 cup vegetable oil, 2 eggs, 1 tsp vanilla extract, 1 cup boiling water',
        instructions: '1. Preheat the oven to 350°F (175°C). 2. Grease and flour a 9-inch round cake pan. 3. In a large bowl, whisk together the flour, sugar, cocoa powder, baking powder, baking soda, and salt. 4. Add the milk, vegetable oil, eggs, and vanilla extract and beat until smooth. 5. Gradually add the boiling water and mix until well combined. 6. Pour the batter into the prepared pan. 7. Bake for 30-35 minutes, or until a toothpick inserted into the center comes out clean. 8. Allow the cake to cool in the pan for 10 minutes, then remove from the pan and cool completely on a wire rack. 9. Frost with your favorite chocolate frosting and serve.',
        preptime: 60,
        servings: 8,
        image: 'https://picsum.photos/seed/chocolate-cake/1600/900',
        creator: '67a4eda0d77031cbaa4c867d',
    },
    {
        title: 'Grilled Cheese Sandwich - seed',
        description: 'A classic grilled cheese sandwich with gooey melted cheese and crispy golden bread. Perfect for a quick and comforting meal.',
        ingredients: '2 slices of bread, 2 slices of cheese, 1 tbsp butter',
        instructions: '1. Heat a skillet over medium heat. 2. Butter one side of each slice of bread. 3. Place one slice of bread, buttered side down, in the skillet. 4. Top with the cheese slices and the other slice of bread, buttered side up. 5. Cook until the bread is golden brown and the cheese is melted, about 2-3 minutes per side. 6. Serve immediately.',
        preptime: 10,
        servings: 1,
        image: 'https://picsum.photos/seed/grilled-cheese/1600/900',
        creator: '67a4eda0d77031cbaa4c867d',
    },
    {
        title: 'Tomato Soup - seed',
        description: 'A warm and comforting tomato soup that is perfect for a chilly day. Serve with a grilled cheese sandwich for a classic combination.',
        ingredients: '2 tbsp olive oil, 1 onion, 2 cloves garlic, 1 carrot, 2 cans (28 oz) crushed tomatoes, 2 cups vegetable broth, 1 tsp sugar, 1 tsp dried basil, salt, pepper, fresh basil for garnish',
        instructions: '1. In a large pot, heat the olive oil over medium heat. 2. Add the chopped onion, garlic, and carrot and sauté until softened. 3. Stir in the crushed tomatoes, vegetable broth, sugar, dried basil, salt, and pepper. 4. Bring to a boil, then reduce the heat and simmer for 20-25 minutes. 5. Use an immersion blender to blend the soup until smooth. 6. Serve hot, garnished with fresh basil.',
        preptime: 30,
        servings: 4,
        image: 'https://picsum.photos/seed/tomato-soup/1600/900',
        creator: '67a4eda0d77031cbaa4c867d',
    },
    {
        title: 'Omelette - seed',
        description: 'A fluffy and delicious omelette filled with your favorite ingredients. Perfect for a quick and satisfying breakfast or brunch.',
        ingredients: '3 eggs, 1/4 cup milk, salt, pepper, 1/4 cup shredded cheese, 1/4 cup diced ham, 1/4 cup chopped vegetables (bell peppers, onions, mushrooms), 1 tbsp butter',
        instructions: '1. In a bowl, whisk together the eggs, milk, salt, and pepper. 2. Heat the butter in a non-stick skillet over medium heat. 3. Pour the egg mixture into the skillet and cook until the edges start to set. 4. Sprinkle the cheese, ham, and vegetables over one half of the omelette. 5. Fold the other half of the omelette over the filling. 6. Cook for another 1-2 minutes, until the cheese is melted and the eggs are fully cooked. 7. Slide the omelette onto a plate and serve immediately.',
        preptime: 10,
        servings: 1,
        image: 'https://picsum.photos/seed/omelette/1600/900',
        creator: '67a4eda0d77031cbaa4c867d',
    },
    {
        title: 'BBQ Ribs - seed',
        description: 'Tender and flavorful BBQ ribs that are perfect for a summer cookout. Serve with your favorite sides for a complete meal.',
        ingredients: '2 racks of pork ribs, 1 cup BBQ sauce, 1/4 cup brown sugar, 1 tbsp paprika, 1 tbsp garlic powder, 1 tbsp onion powder, 1 tsp salt, 1 tsp pepper',
        instructions: '1. Preheat the oven to 300°F (150°C). 2. In a small bowl, mix together the brown sugar, paprika, garlic powder, onion powder, salt, and pepper. 3. Rub the spice mixture all over the ribs. 4. Place the ribs on a baking sheet and cover with foil. 5. Bake for 2 1/2 to 3 hours, until the ribs are tender. 6. Remove the foil and brush the ribs with BBQ sauce. 7. Increase the oven temperature to 400°F (200°C) and bake for another 15-20 minutes, until the sauce is caramelized. 8. Serve hot with additional BBQ sauce on the side.',
        preptime: 120,
        servings: 4,
        image: 'https://picsum.photos/seed/bbq-ribs/1600/900',
        creator: '67a4eda0d77031cbaa4c867d',
    },
    {
        title: 'Margarita Pizza - seed',
        description: 'A classic Italian pizza with a simple and delicious combination of tomato sauce, mozzarella cheese, and fresh basil.',
        ingredients: 'Pizza dough, 1/2 cup tomato sauce, 1 cup shredded mozzarella cheese, fresh basil leaves, olive oil, salt, pepper',
        instructions: '1. Preheat the oven to 475°F (245°C). 2. Roll out the pizza dough on a floured surface. 3. Transfer the dough to a pizza stone or baking sheet. 4. Spread the tomato sauce evenly over the dough. 5. Sprinkle the mozzarella cheese on top. 6. Bake for 10-12 minutes, until the crust is golden brown and the cheese is melted and bubbly. 7. Remove from the oven and top with fresh basil leaves. 8. Drizzle with olive oil and season with salt and pepper. 9. Slice and serve hot.',
        preptime: 20,
        servings: 2,
        image: 'https://picsum.photos/seed/margarita-pizza/1600/900',
        creator: '67a4eda0d77031cbaa4c867d',
    },
    {
        title: 'Fish Tacos - seed',
        description: 'Fresh and tasty fish tacos with a zesty lime and cilantro slaw. Perfect for a light and flavorful meal.',
        ingredients: 'Taco shells, 400g fish fillets (such as cod or tilapia), 1/2 cup flour, 1 tsp chili powder, 1 tsp cumin, salt, pepper, 1/4 cup mayonnaise, 1/4 cup sour cream, 1 lime, 1/4 cup chopped cilantro, 2 cups shredded cabbage, olive oil',
        instructions: '1. In a shallow dish, mix together the flour, chili powder, cumin, salt, and pepper. 2. Dredge the fish fillets in the flour mixture, shaking off any excess. 3. Heat the olive oil in a large pan over medium-high heat. 4. Cook the fish fillets for 3-4 minutes per side, until golden brown and cooked through. 5. In a small bowl, mix together the mayonnaise, sour cream, lime juice, and chopped cilantro. 6. In a large bowl, toss the shredded cabbage with the dressing. 7. Warm the taco shells according to the package instructions. 8. Fill each taco shell with a piece of fish and top with the slaw. 9. Serve immediately.',
        preptime: 20,
        servings: 3,
        image: 'https://picsum.photos/seed/fish-tacos/1600/900',
        creator: '67a4eda0d77031cbaa4c867d',
    },
    {
        title: 'Lemonade - seed',
        description: 'Refreshing homemade lemonade that is perfect for a hot summer day. Sweet, tangy, and incredibly easy to make.',
        ingredients: '6 lemons, 1 cup sugar, 6 cups water, ice, lemon slices for garnish',
        instructions: '1. Juice the lemons to make about 1 cup of lemon juice. 2. In a small saucepan, combine the sugar and 1 cup of water. 3. Heat over medium heat, stirring until the sugar is dissolved, to make a simple syrup. 4. In a large pitcher, combine the lemon juice, simple syrup, and the remaining 5 cups of water. 5. Stir well and refrigerate until chilled. 6. Serve over ice, garnished with lemon slices.',
        preptime: 10,
        servings: 4,
        image: 'https://picsum.photos/seed/lemonade/1600/900',
        creator: '67a4eda0d77031cbaa4c867d',
    },
    {
        title: 'Apple Pie - seed',
        description: 'Classic apple pie with a flaky crust and a sweet, spiced apple filling. Perfect for dessert or a special occasion.',
        ingredients: '6 cups sliced apples, 1 cup sugar, 2 tbsp flour, 1 tsp cinnamon, 1/4 tsp nutmeg, 1/4 tsp salt, 1 tbsp lemon juice, 2 pie crusts, 2 tbsp butter, 1 egg, 1 tbsp milk',
        instructions: '1. Preheat the oven to 425°F (220°C). 2. In a large bowl, toss the sliced apples with the sugar, flour, cinnamon, nutmeg, salt, and lemon juice. 3. Roll out one pie crust and fit it into a 9-inch pie plate. 4. Fill the crust with the apple mixture and dot with butter. 5. Roll out the second pie crust and place it over the filling. 6. Trim and crimp the edges to seal. 7. Cut a few slits in the top crust to allow steam to escape. 8. In a small bowl, beat the egg with the milk and brush it over the top crust. 9. Bake for 45-50 minutes, until the crust is golden brown and the filling is bubbly. 10. Allow the pie to cool before serving.',
        preptime: 90,
        servings: 8,
        image: 'https://picsum.photos/seed/apple-pie/1600/900',
        creator: '67a4eda0d77031cbaa4c867d',
    }
];

module.exports = seedrecipes;